# The Basics of NumPy and Pandas

**Numpy** is the core library for scientific computing in Python. It provides a high-performance multidimensional **array object**, and tools for working with these arrays. If you are already familiar with MATLAB, you might find this [tutorial](http://wiki.scipy.org/NumPy_for_Matlab_Users) useful to get started with Numpy.

###Why use Numpy Arrays instead of Lists?


*   Data types: Arrays in NumPy are **homogeneous**, meaning all elements must be of the same data type (e.g., integers, floats), whereas lists can contain elements of different data types.

*   Memory efficiency: Arrays are more **memory efficient** compared to lists because they store data in a contiguous block of memory. Lists, on the other hand, store references to objects in memory, which can result in more memory overhead.

*   Performance: Operations on arrays are generally faster and more efficient than operations on lists, especially for large datasets, due to **NumPy's implementation in C** and optimized algorithms.

*   Functionality: NumPy arrays come with a wide range of **built-in functions and methods** for mathematical operations, linear algebra, statistical analysis, and more. Lists have a more limited set of built-in functions and methods.




To use Numpy, we first need to import the numpy package. By convention, we import it using the alias np. Then, when we want to use modules or methods in this library, we preface them with np.



In [1]:
import numpy as np

### Arrays and array construction

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can create a `numpy` array by passing a Python list to `np.array()`.

In [2]:
a = np.array([1, 2, 3])  # Create a rank 1 array

This creates the array we can see on the right here:

![](http://jalammar.github.io/images/numpy/create-numpy-array-1.png)

In [3]:
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5                 # Change an element of the array
print(a)

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


To create a `numpy` array with more dimensions, we can pass nested lists, like this:

![](http://jalammar.github.io/images/numpy/numpy-array-create-2d.png)

![](http://jalammar.github.io/images/numpy/numpy-3d-array.png)

In [4]:
b = np.array([[1,2],[3,4]])   # Create a rank 2 array
print(b)
print(b.shape)

[[1 2]
 [3 4]]
(2, 2)


In [5]:
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)
print(c.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


There are often cases when we want numpy to initialize the values of the array for us. numpy provides methods like `ones()`, `zeros()`, and `random.random()` for these cases. We just pass them the number of elements we want it to generate:

![](http://jalammar.github.io/images/numpy/create-numpy-array-ones-zeros-random.png)

Sometimes, we need an array of a specific shape with “placeholder” values that we plan to fill in with the result of a computation. The `zeros` or `ones` functions are handy for this:

In [6]:
a = np.ones(3)  # Create an array of all ones
print(a)
b=np.random.random(3)
print(b)

[1. 1. 1.]
[0.43889129 0.16352568 0.89593897]


We can also use these methods to produce multi-dimensional arrays, as long as we pass them a tuple describing the dimensions of the matrix we want to create:

![](http://jalammar.github.io/images/numpy/numpy-matrix-ones-zeros-random.png)



In [7]:
a = np.zeros((2,2))  # Create an array of all zeros
print(a)
b = np.ones((1,2))   # Create an array of all ones
print(b)
c = np.random.random((2,2)) # Create an array filled with random values
print(c)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[0.61160161 0.36276462]
 [0.7684433  0.55324743]]


Numpy also has two useful functions for creating sequences of numbers: `arange` and `linspace`.

The `arange` function accepts three arguments, which define the start value, stop value of a half-open interval, and step size. (The default step size, if not explicitly specified, is 1; the default start value, if not explicitly specified, is 0.)

The `linspace` function is similar, but we can specify the number of values instead of the step size, and it will create a sequence of evenly spaced values.

In [8]:
f = np.arange(10,50,5)   # Create an array of values starting at 10 in increments of 5
print(f)

[10 15 20 25 30 35 40 45]


Note this ends on 45, not 50 (does not include the top end of the interval).

In [9]:
g = np.linspace(0., 1., num=5)
print(g)

[0.   0.25 0.5  0.75 1.  ]


In [10]:
# Using linspace
linspace_array = np.linspace(0, 10, 5)
print("Linspace Array:", linspace_array)

# Using arange
arange_array = np.arange(0, 10, 2)
print("Arange Array:", arange_array)

Linspace Array: [ 0.   2.5  5.   7.5 10. ]
Arange Array: [0 2 4 6 8]


Sometimes, we may want to construct an array from existing arrays by “stacking” the existing arrays, either vertically or horizontally. We can use `vstack()` (or `row_stack`) and `hstack()` (or `column_stack`), respectively.

In [11]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
a = np.array([[7], [8], [9]])
b = np.array([[4], [5], [6]])
np.hstack((a,b))

array([[7, 4],
       [8, 5],
       [9, 6]])

## NumPy Array Attributes

In [13]:
x1=np.array([5,6,7,8,9])
print(x1.shape)
print(x1)

(5,)
[5 6 7 8 9]


Each array has attributes ``ndim`` (the number of dimensions), ``shape`` (the size of each dimension), and ``size`` (the total size of the array):

In [14]:
print("x1 ndim: ", x1.ndim)
print("x1 shape:", x1.shape)
x2 = np.random.random((3, 4))  # Two-dimensional array
print("x2 size: ", x2.size)

x1 ndim:  1
x1 shape: (5,)
x2 size:  12


####Datatypes

Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

In [15]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int64)  # Force a particular datatype

print(x.dtype, y.dtype, z.dtype)

int64 float64 int64


You can read all about numpy datatypes in the [documentation](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

## Array Indexing: Accessing Single Elements

If you are familiar with Python's standard list indexing, indexing in NumPy will feel quite familiar.
In a one-dimensional array, the $i^{th}$ value (counting from zero) can be accessed by specifying the desired index in square brackets, just as with Python lists:

In [16]:
x1

array([5, 6, 7, 8, 9])

In [17]:
x1[0]

5

In [18]:
x1[4]

9

To index from the end of the array, you can use negative indices:

In [19]:
x1[-1]

9

In [20]:
x1[-2]

8

In a multi-dimensional array, items can be accessed using a comma-separated tuple of indices:

In [21]:
x2

array([[0.09337151, 0.72548805, 0.75470484, 0.31305357],
       [0.47743438, 0.96614724, 0.21691275, 0.5601033 ],
       [0.62484149, 0.88439898, 0.60727937, 0.59125463]])

In [22]:
x2[0, 0]

0.0933715069841694

In [23]:
x2[2, 0]

0.6248414927055272

In [24]:
x2[2, -1]

0.5912546251750206

Values can also be modified using any of the above index notation:

In [25]:
x2[0, 0] = 12
x2

array([[12.        ,  0.72548805,  0.75470484,  0.31305357],
       [ 0.47743438,  0.96614724,  0.21691275,  0.5601033 ],
       [ 0.62484149,  0.88439898,  0.60727937,  0.59125463]])

Keep in mind that, unlike Python lists, NumPy arrays have a fixed type.
This means, for example, that if you attempt to insert a floating-point value to an integer array, the value will be silently truncated. Don't be caught unaware by this behavior!

In [26]:
print(x1)
x1[0] = 3.14159  # this will be truncated!
x1

[5 6 7 8 9]


array([3, 6, 7, 8, 9])

## Array Slicing: Accessing Subarrays

Just as we can use square brackets to access individual array elements, we can also use them to access subarrays with the *slice* notation, marked by the colon (``:``) character.
The NumPy slicing syntax follows that of the standard Python list; to access a slice of an array ``x``, use this:
``` python
x[start:stop:step]
```
If any of these are unspecified, they default to the values ``start=0``, ``stop=``*``size of dimension``*, ``step=1``.
We'll take a look at accessing sub-arrays in one dimension and in multiple dimensions.

### One-dimensional subarrays

In [27]:
x = np.arange(20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [28]:
x[:5]  # first five elements

array([0, 1, 2, 3, 4])

In [29]:
x[5:]  # elements after index 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [30]:
x[4:7]  # middle sub-array

array([4, 5, 6])

In [31]:
x[::2]  # every other element  # What if I want odd numbers?

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

A potentially confusing case is when the ``step`` value is negative.
In this case, the defaults for ``start`` and ``stop`` are swapped.
This becomes a convenient way to reverse an array:

In [32]:
x[::-1]  # all elements, reversed

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

### Multi-dimensional subarrays

Multi-dimensional slices work in the same way, with multiple slices separated by commas.
For example:

In [33]:
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x2


array([[4, 1, 2, 0],
       [2, 7, 4, 1],
       [8, 2, 4, 1]])

In [34]:
x2[:2, :3]  # two rows, three columns

array([[4, 1, 2],
       [2, 7, 4]])

In [35]:
x2[:3, ::2]  # all rows, every other column

array([[4, 2],
       [2, 4],
       [8, 4]])

Finally, subarray dimensions can even be reversed together:

In [36]:
x2[::-1, ::-1]

array([[1, 4, 2, 8],
       [1, 4, 7, 2],
       [0, 2, 1, 4]])

#### Accessing array rows and columns

One commonly needed routine is accessing of single rows or columns of an array.
This can be done by combining indexing and slicing, using an empty slice marked by a single colon (``:``):

In [37]:
print(x2[:, 0])  # first column of x2

[4 2 8]


In [38]:
print(x2[0, :])  # first row of x2

[4 1 2 0]


In the case of row access, the empty slice can be omitted for a more compact syntax:

In [39]:
print(x2[0])  # equivalent to x2[0, :]

[4 1 2 0]


### Subarrays as no-copy views

One important–and extremely useful–thing to know about array slices is that they return *views* rather than *copies* of the array data.
This is one area in which NumPy array slicing differs from Python list slicing: in lists, slices will be copies.
Consider our two-dimensional array from before:

In [40]:
print(x2)

[[4 1 2 0]
 [2 7 4 1]
 [8 2 4 1]]


Let's extract a $2 \times 2$ subarray from this:

In [41]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[4 1]
 [2 7]]


Now if we modify this subarray, we'll see that the original array is changed! Observe:

In [42]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  1]
 [ 2  7]]


In [43]:
print(x2)

[[99  1  2  0]
 [ 2  7  4  1]
 [ 8  2  4  1]]


This default behavior is actually quite useful: it means that when we work with large datasets, we can access and process pieces of these datasets without the need to copy the underlying data buffer.

### Creating copies of arrays

Despite the nice features of array views, it is sometimes useful to instead explicitly copy the data within an array or a subarray. This can be most easily done with the ``copy()`` method:

In [44]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  1]
 [ 2  7]]


If we now modify this subarray, the original array is not touched:

In [45]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  1]
 [ 2  7]]


In [46]:
print(x2)

[[99  1  2  0]
 [ 2  7  4  1]
 [ 8  2  4  1]]


## Reshaping of Arrays

Another useful type of operation is reshaping of arrays.
The most flexible way of doing this is with the ``reshape`` method.
For example, if you want to put the numbers 1 through 9 in a $3 \times 3$ grid, you can do the following:

In [47]:
grid = np.arange(1, 10).reshape((3,3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [48]:
grid = np.arange(1,10)
print(grid)
grid = grid.reshape((3,3))
print(grid)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Note that for this to work, the size of the initial array must match the size of the reshaped array.

Another common reshaping pattern is the conversion of a one-dimensional array into a two-dimensional row or column matrix.
This can be done with the ``reshape`` method, or more easily done by making use of the ``newaxis`` keyword within a slice operation:

In [49]:
x = np.array([1, 2, 3])
# row vector via reshape
print(x.shape)
print(x)
x = x.reshape((3,1))
print(x.shape)
print(x)

(3,)
[1 2 3]
(3, 1)
[[1]
 [2]
 [3]]


In [50]:
x = np.array([1, 2, 3])
# row vector via newaxis
x = x[np.newaxis, :]   #It adds an axis of length 1 to the array, effectively increasing its dimensionality.
print(x)
print(x.shape)

[[1 2 3]]
(1, 3)


In [51]:
x = np.array([1, 2, 3])
# column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [52]:
# column vector via newaxis
x = np.array([1, 2, 3])
x=x[:, np.newaxis]
print(x.shape)

(3, 1)


You will come across such transformations throughout any data science problem.


## Array Concatenation and Splitting

All of the preceding routines worked on single arrays. It's also possible to combine multiple arrays into one, and to conversely split a single array into multiple arrays. We'll take a look at those operations here.

### Concatenation of arrays

Concatenation, or joining of two arrays in NumPy, is primarily accomplished using the routines ``np.concatenate``, ``np.vstack``, and ``np.hstack``.
``np.concatenate`` takes a tuple or list of arrays as its first argument, as we can see here:

In [53]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

You can also concatenate more than two arrays at once:

In [54]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


It can also be used for two-dimensional arrays:

In [55]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

print(grid.shape)

(2, 3)


In [56]:
# concatenate along the first axis
new_grid = np.concatenate([grid, grid], axis=0)
new_grid.shape

(4, 3)

In [57]:
# concatenate along the second axis (zero-indexed)
new_grid_col = np.concatenate([grid, grid], axis=1)
new_grid_col.shape

(2, 6)

Numpy also provides many useful functions for performing computations on arrays, such as `min()`, `max()`, `sum()`, and others:

![](http://jalammar.github.io/images/numpy/numpy-matrix-aggregation-1.png)

In [58]:
data = np.array([[1, 2], [3, 4], [5, 6]])

print(np.max(data))  # Compute max of all elements; prints "6"
print(np.min(data))  # Compute min of all elements; prints "1"
print(np.sum(data))  # Compute sum of all elements; prints "21"

6
1
21


Not only can we aggregate all the values in a matrix using these functions, but we can also aggregate across the rows or columns by using the `axis` parameter:

![](http://jalammar.github.io/images/numpy/numpy-matrix-aggregation-4.png)

In [59]:
data = np.array([[1, 2], [5, 3], [4, 6]])

print(np.max(data, axis=0))  # Compute max of each column; prints "[5 6]"
print(np.max(data, axis=1))  # Compute max of each row; prints "[2 5 6]"

[5 6]
[2 5 6]


Let's look at a practical example using the numpy attributes we just discussed 💻

## Practice Questions for numpy
1. Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.
2. Find common elements between A and B. [Hint : Intersection of two sets]
3. Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]
4. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0
```
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
```

In [60]:
## Optional Practice Question

#Find the mean of a numeric column grouped by a categorical column in a 2D numpy array

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')


numeric_column = iris[:, 1].astype('float')  # sepalwidth
grouping_column = iris[:, 4]  # species

output = []
"""Your code goes here"""

output

[]

## Starting with Pandas

Pandas is a powerful and popular open-source Python library used for data manipulation (cleaning, filtering, sorting, reshaping, restructuring, aggregating, joining) and analysis. It provides data structures and functions designed to make working with structured (tabular) data easy and intuitive.

Check out the [documentation](https://pandas.pydata.org/docs/reference/index.html) as you code.

In [61]:
#we start from the very basics...import!

import pandas as pd
import numpy as np

The **DataFrame** is a two-dimensional labeled data structure with columns of potentially different types, similar to a spreadsheet or SQL table. It provides powerful indexing, slicing, and reshaping capabilities, making it easy to manipulate and analyze data.

## PART 1: Getting and Knowing your Data


In [62]:
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'

chipo = pd.read_csv(url, sep='\t')

### See the first 10 entries

In [63]:
chipo.head(10)  #Returns the first 10 rows

order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   
5         3         1                           Chicken Bowl   
6         3         1                          Side of Chips   
7         4         1                          Steak Burrito   
8         4         1                       Steak Soft Tacos   
9         5         1                          Steak Burrito   

                                  choice_description item_price  
0                                                NaN     $2.39   
1                                       [Clementine]     $3.39   
2                                            [Apple]     $3.39   
3                                                NaN     $2.39   
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98   
5  [Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...    $10.98   
6                                                NaN     $1.69   
7  [Tomatillo Red Chili Salsa, [Fajita Vegetables...    $11.75   
8  [Tomatillo Green Chili Salsa, [Pinto Beans, Ch...     $9.25   
9  [Fresh Tomato Salsa, [Rice, Black Beans, Pinto...     $9.25

### Print the last elements of the data set.

In [64]:
chipo.tail()   #Returns the last 5 rows

order_id  quantity           item_name  \
4617      1833         1       Steak Burrito   
4618      1833         1       Steak Burrito   
4619      1834         1  Chicken Salad Bowl   
4620      1834         1  Chicken Salad Bowl   
4621      1834         1  Chicken Salad Bowl   

                                     choice_description item_price  
4617  [Fresh Tomato Salsa, [Rice, Black Beans, Sour ...    $11.75   
4618  [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...    $11.75   
4619  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...    $11.25   
4620  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...     $8.75   
4621  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...     $8.75

### What is the number of observations in the dataset?

In [65]:
chipo.shape    #Return a tuple representing the dimensionality of the DataFrame.   #How to access no of rows and columns?

(4622, 5)

### Another way

In [66]:
chipo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   order_id            4622 non-null   int64 
 1   quantity            4622 non-null   int64 
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.7+ KB


### What is the number of columns in the dataset?

In [67]:
chipo.shape[1]

5

### What are the different columns in our dataset?

In [68]:
chipo.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

In [69]:
chipo.index

RangeIndex(start=0, stop=4622, step=1)

### How many items were orderd in total?

In [70]:
total_items_orders = chipo.quantity.sum()
total_items_orders

4972

### Check the item price type

In [71]:
chipo.item_price.dtype
# It is a python object

dtype('O')

How much was the revenue for the period in the dataset?

In [72]:
#chipo['item_price'] = chipo['item_price'].str[1:]
#chipo['item_price'] = pd.to_numeric(chipo['item_price'])

In [73]:
revenue = (chipo['quantity']* chipo['item_price'])
revenue = revenue.sum()

print('Revenue was: $' + str(np.round(revenue,2)))

UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U31146'), dtype('float64')) -> None

### How many orders were made in the period?

In [ ]:
orders = chipo.order_id.value_counts().count()         # value_counts: returns the frequency count of unique values in the 'order_id' column of the DataFrame chipo
orders

### How many different items are sold?


In [ ]:
chipo.item_name.value_counts().count()

## PART B: Filtering and Sorting Data

### What is the price of each item?


In [ ]:
chipo[(chipo['item_name'] == 'Chicken Bowl') & (chipo['quantity'] == 1)]

### Sort by the name of the item

In [ ]:
chipo.item_name.sort_values()

### OR

In [ ]:
chipo.sort_values(by = "item_name")

### What was the quantity of the most expensive item ordered?

In [ ]:
chipo.sort_values(by = "item_price", ascending = False).head(1)


### How many times was a Veggie Salad Bowl ordered?

In [ ]:
chipo_salad = chipo[chipo.item_name == "Veggie Salad Bowl"]
len(chipo_salad)

### Trying some different dataset

In [ ]:
drinks = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/drinks.csv')
drinks.head()

### Which continent drinks more beer on average?

In [ ]:
drinks.groupby('continent').beer_servings.mean()

### For each continent print the statistics for wine consumption.

In [ ]:
drinks.groupby('continent').wine_servings.describe()

### Print the median alcohol consumption per continent for every column

In [ ]:
drinks.groupby('continent').mean()

### Print the median alcohol consumption per continent for every column


In [ ]:
drinks.groupby('continent').median()

### Print the mean, min and max values for spirit consumption.

In [ ]:
drinks.groupby('continent').spirit_servings.agg(['mean', 'min', 'max'])

### Trying some more different functionalities

In [76]:
csv_url = 'https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/04_Apply/Students_Alcohol_Consumption/student-mat.csv'
df = pd.read_csv(csv_url)
stud_alcoh = df.loc[: , "school":"guardian"]
stud_alcoh.head()

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher   
1     GP   F   17       U     GT3       T     1     1  at_home     other   
2     GP   F   15       U     LE3       T     1     1  at_home     other   
3     GP   F   15       U     GT3       T     4     2   health  services   
4     GP   F   16       U     GT3       T     3     3    other     other   

   reason guardian  
0  course   mother  
1  course   father  
2   other   mother  
3    home   mother  
4    home   father

In [77]:
capitalizer = lambda q: q.capitalize()  #A lambda function in Python is a small anonymous function that can have any number of arguments, but can only have one expression.
                                        #They are defined using the lambda keyword, followed by a list of arguments, a colon, and then the expression to be evaluated.
                                        # Lambda functions are often used when you need a simple function for a short period of time.

In [78]:
stud_alcoh['Mjob'].apply(capitalizer)
stud_alcoh['Fjob'].apply(capitalizer)
stud_alcoh.tail()

school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
390     MS   M   20       U     LE3       A     2     2  services  services   
391     MS   M   17       U     LE3       T     3     1  services  services   
392     MS   M   21       R     GT3       T     1     1     other     other   
393     MS   M   18       R     LE3       T     3     2  services     other   
394     MS   M   19       U     LE3       T     1     1     other   at_home   

     reason guardian  
390  course    other  
391  course   mother  
392  course    other  
393  course   mother  
394  course   father

In [79]:
stud_alcoh['Mjob'] = stud_alcoh['Mjob'].apply(capitalizer)
stud_alcoh['Fjob'] = stud_alcoh['Fjob'].apply(capitalizer)
stud_alcoh.tail()

school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
390     MS   M   20       U     LE3       A     2     2  Services  Services   
391     MS   M   17       U     LE3       T     3     1  Services  Services   
392     MS   M   21       R     GT3       T     1     1     Other     Other   
393     MS   M   18       R     LE3       T     3     2  Services     Other   
394     MS   M   19       U     LE3       T     1     1     Other   At_home   

     reason guardian  
390  course    other  
391  course   mother  
392  course    other  
393  course   mother  
394  course   father

### Here instead of just using the existing the data, we will create our own dataframe/dataseries

**pd.Series** is a one-dimensional labeled array-like data structure in pandas. It can hold data of any type (integers, floats, strings, etc.) and is similar to a **one-dimensional NumPy array** or a Python list. However, unlike a NumPy array, a pd.Series can have *custom row labels*, which are referred to as the index.

In [ ]:
a = pd.Series([1,2,3])
a

You can specify custom index labels for a pandas Series by passing a list of index labels to the index parameter when creating the Series.

In [ ]:
data = [10, 20, 30]
custom_index = ['A', 'B', 'C']
s = pd.Series(data, index=custom_index)
s

In [ ]:
print('Data passed as a list')
df_list = pd.DataFrame([['May1', 32], ['May2', 35], ['May3', 40], ['May4', 50]])
print(df_list)

In [ ]:
print('Data passed as dictionary')
df_dict = pd.DataFrame({"A": [1, 2, 3], "B": [4, 5, 6]},dtype = float)
print(df_dict)

In [ ]:
# Rename columns

df_dict.rename(columns={'A': 'a'})

# inplace by default is false
# if inplace = True is not set then the changes are not made on the original df but only a temp df is made with changes
df_dict

In [ ]:
# changes made for original df

df_dict.rename(columns={'A': 'a'}, inplace=True)
df_dict


In [ ]:
# Reset column names
# Tip: remember to pass the entire list in this case

df_dict.columns = ['a', 'b']
df_dict.head()

In [ ]:
# Defining columns, index during dataframe creation

df_temp = pd.DataFrame([['October 1', 67], ['October 2', 72], ['October 3', 58], ['October 4', 69], ['October 5', 77]], index = ['Day 1', 'Day 2', 'Day 3', 'Day 4', 'Day 5'], columns = ['Month', 'Temperature'])
df_temp


## Practice Questions for Pandas

1. From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).

```
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```

2. Replace missing values in Min.Price and Max.Price columns with their respective mean.

```
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```

3. How to get the rows of a dataframe with row sum > 100?

```
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
```

In [74]:
#1 From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).
import pandas as pd
import numpy as np

In [95]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df.head(10)
df_filter = df.loc[::20]
filtered_df = df_filter[['Manufacturer','Model','Type']]
#filtered_df = df.loc[::20, ['Manufacturer', 'Model', 'Type']]

filtered_df
#df_filter

Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small

In [96]:
df.head(10)

Manufacturer       Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0        Acura     Integra    Small       12.9   15.9       18.8      25.0   
1          NaN      Legend  Midsize       29.2   33.9       38.7      18.0   
2         Audi          90  Compact       25.9   29.1       32.3      20.0   
3         Audi         100  Midsize        NaN   37.7       44.6      19.0   
4          BMW        535i  Midsize        NaN   30.0        NaN      22.0   
5        Buick     Century  Midsize       14.2   15.7       17.3      22.0   
6        Buick     LeSabre    Large       19.9   20.8        NaN      19.0   
7        Buick  Roadmaster    Large       22.6   23.7       24.9      16.0   
8        Buick     Riviera  Midsize       26.3   26.3       26.3      19.0   
9     Cadillac     DeVille    Large       33.0   34.7       36.3      16.0   

   MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0         31.0                None      Front  ...        5.0   177.0   
1         25.0  Driver & Passenger      Front  ...        5.0   195.0   
2         26.0         Driver only      Front  ...        5.0   180.0   
3         26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4         30.0                 NaN       Rear  ...        4.0   186.0   
5         31.0         Driver only        NaN  ...        6.0   189.0   
6         28.0         Driver only      Front  ...        6.0   200.0   
7         25.0         Driver only       Rear  ...        6.0   216.0   
8         27.0         Driver only      Front  ...        5.0   198.0   
9         25.0         Driver only      Front  ...        6.0   206.0   

   Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0      102.0   68.0         37.0           26.5           NaN  2705.0   
1      115.0   71.0         38.0           30.0          15.0  3560.0   
2      102.0   67.0         37.0           28.0          14.0  3375.0   
3      106.0    NaN         37.0           31.0          17.0  3405.0   
4      109.0   69.0         39.0           27.0          13.0  3640.0   
5      105.0   69.0         41.0           28.0          16.0     NaN   
6      111.0   74.0         42.0           30.5          17.0  3470.0   
7      116.0   78.0         45.0           30.5          21.0  4105.0   
8      108.0    NaN         41.0           26.5          14.0  3495.0   
9      114.0   73.0         43.0           35.0          18.0  3620.0   

    Origin              Make  
0  non-USA     Acura Integra  
1  non-USA      Acura Legend  
2  non-USA           Audi 90  
3  non-USA          Audi 100  
4  non-USA          BMW 535i  
5      USA     Buick Century  
6      USA     Buick LeSabre  
7      USA  Buick Roadmaster  
8      USA     Buick Riviera  
9      USA  Cadillac DeVille  

[10 rows x 27 columns]

In [99]:
#2 Replace missing values in Min.Price and Max.Price columns with their respective mean.
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df.head()

df['Min.Price'].fillna(df['Min.Price'].mean(), inplace=True)
df['Max.Price'].fillna(df['Max.Price'].mean(), inplace=True)

print(df[['Min.Price', 'Max.Price']].head(10))
df.head(10)

   Min.Price  Max.Price
0  12.900000  18.800000
1  29.200000  38.700000
2  25.900000  32.300000
3  17.118605  44.600000
4  17.118605  21.459091
5  14.200000  17.300000
6  19.900000  21.459091
7  22.600000  24.900000
8  26.300000  26.300000
9  33.000000  36.300000


Manufacturer       Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0        Acura     Integra    Small  12.900000   15.9  18.800000      25.0   
1          NaN      Legend  Midsize  29.200000   33.9  38.700000      18.0   
2         Audi          90  Compact  25.900000   29.1  32.300000      20.0   
3         Audi         100  Midsize  17.118605   37.7  44.600000      19.0   
4          BMW        535i  Midsize  17.118605   30.0  21.459091      22.0   
5        Buick     Century  Midsize  14.200000   15.7  17.300000      22.0   
6        Buick     LeSabre    Large  19.900000   20.8  21.459091      19.0   
7        Buick  Roadmaster    Large  22.600000   23.7  24.900000      16.0   
8        Buick     Riviera  Midsize  26.300000   26.3  26.300000      19.0   
9     Cadillac     DeVille    Large  33.000000   34.7  36.300000      16.0   

   MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0         31.0                None      Front  ...        5.0   177.0   
1         25.0  Driver & Passenger      Front  ...        5.0   195.0   
2         26.0         Driver only      Front  ...        5.0   180.0   
3         26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4         30.0                 NaN       Rear  ...        4.0   186.0   
5         31.0         Driver only        NaN  ...        6.0   189.0   
6         28.0         Driver only      Front  ...        6.0   200.0   
7         25.0         Driver only       Rear  ...        6.0   216.0   
8         27.0         Driver only      Front  ...        5.0   198.0   
9         25.0         Driver only      Front  ...        6.0   206.0   

   Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0      102.0   68.0         37.0           26.5           NaN  2705.0   
1      115.0   71.0         38.0           30.0          15.0  3560.0   
2      102.0   67.0         37.0           28.0          14.0  3375.0   
3      106.0    NaN         37.0           31.0          17.0  3405.0   
4      109.0   69.0         39.0           27.0          13.0  3640.0   
5      105.0   69.0         41.0           28.0          16.0     NaN   
6      111.0   74.0         42.0           30.5          17.0  3470.0   
7      116.0   78.0         45.0           30.5          21.0  4105.0   
8      108.0    NaN         41.0           26.5          14.0  3495.0   
9      114.0   73.0         43.0           35.0          18.0  3620.0   

    Origin              Make  
0  non-USA     Acura Integra  
1  non-USA      Acura Legend  
2  non-USA           Audi 90  
3  non-USA          Audi 100  
4  non-USA          BMW 535i  
5      USA     Buick Century  
6      USA     Buick LeSabre  
7      USA  Buick Roadmaster  
8      USA     Buick Riviera  
9      USA  Cadillac DeVille  

[10 rows x 27 columns]

In [106]:
#3 How to get the rows of a dataframe with row sum > 100?
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
print(df.shape)
df.head()
rows_with_sum_over_100 = df[df.sum(axis=1) > 100]

rows_with_sum_over_100

(15, 4)


0   1   2   3
0   31  35  39  30
1   22  28  26  33
2   24  32  20  32
4   24  26  28  25
5   23  38  35  33
6   28  38  17  18
12  38  37  23  25
14  20  33  26  37

In [111]:
#4. Create a 4x4 NumPy array filled with random integers between 1 and 100. Then, reshape this array into two separate 2D arrays,
#where one represents the rows and the other represents the columns.
#Write a function, preferably using a lambda function, to calculate the sum of each row and each column separately,
#and return the results as two separate NumPy arrays
array=np.random.randint(1,101,size=(4,4))
array
row_summarize = lambda x: np.sum(x,axis=1)
column_summarize = lambda x: np.sum(x,axis=0)
row_sums = row_summarize(array)
column_sums = column_summarize(array)


# Calculating the sum of each row and each column separately using lambda functions
#row_sums = np.apply_along_axis(lambda x: np.sum(x), 1, original_array)
#column_sums = np.apply_along_axis(lambda x: np.sum(x), 0, original_array)

array, row_sums, column_sums

#capitalizer = lambda q: q.capitalize()  #A lambda function in Python is a small anonymous function that can have any number of arguments, but can only have one expression.
                                        #They are defined using the lambda keyword, followed by a list of arguments, a colon, and then the expression to be evaluated.
                                        # Lambda functions are often used when you need a simple function for a short period of time.

#stud_alcoh['Mjob'] = stud_alcoh['Mjob'].apply(capitalizer)
#stud_alcoh['Fjob'] = stud_alcoh['Fjob'].apply(capitalizer)
#stud_alcoh.tail()

(array([[43, 79, 20, 47],
        [10, 49, 22, 21],
        [63,  8, 61, 66],
        [22,  6,  4,  1]]),
 array([189, 102, 198,  33]),
 array([138, 142, 107, 135]))